EnsJobeetBundle_job:
    resource: "@EnsJobeetBundle/Resources/config/routing/job.yml"
    prefix: /job

EnsJobeetBundle_homepage:
    path:  /
    defaults: { _controller: EnsJobeetBundle:Job:index }
