EnsJobeetBundle_job:
    resource: "@EnsJobeetBundle/Resources/config/routing/job.yml"
    prefix: /job

EnsJobeetBundle_homepage:
    path:  /
    defaults: { _controller: EnsJobeetBundle:Job:index }

EnsJobeetBundle_category:
    pattern:  /category/{slug}/{page}
    defaults: { _controller: EnsJobeetBundle:Category:show, page:1 }

admin:
    resource: '@SonataAdminBundle/Resources/config/routing/sonata_admin.xml'
    prefix: /admin

_sonata_admin:
    resource: .
    type: sonata_admin
    prefix: /admin

login:
    pattern:   /login
    defaults:  { _controller: EnsJobeetBundle:Default:login }
login_check:
    pattern:   /login_check

logout:
    pattern: /logout